version: "3.9"

services:
  airflow:
    image: apache/airflow:3.1.7-python3.10
    container_name: airflow
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      # Enable OpenLineage backend
      AIRFLOW__LINEAGE__BACKEND: airflow.lineage.backend.openlineage.OpenLineageBackend
      AIRFLOW__OPENLINEAGE__URL: http://marquez:9000/api/v1
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: airflow standalone

